// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlipCardController from "./flip_card_controller"
application.register("flip-card", FlipCardController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)
